services:
  vintage_story:
    image: neebz/vintage-story-server:latest
    ports:
      - "42420:42420/tcp"
      - "42420:42420/udp"
    volumes:
      - /path/on/host:/app/data
      - vintage-story-game-files:/app/server  # Docker-managed named volume
    environment:
      - VERSION=1.21.0-rc.1
      - CHANNEL=unstable
    user: "1000:1000"
volumes:
  vintage-story-game-files:
