services:
  vintage_story:
    image: neebz/vintage-story-server:latest
    ports:
      - "42420:42420/tcp"
      - "42420:42420/udp"
    volumes:
      - path-on-host/server_files:/app/server_files
      - path-on-host/game_files:/app/game_files
    environment:
      - VERSION=1.22.2
      - CHANNEL=stable
    user: "1000:1000"