services:
  vintage_story:
    image:  neebz/vintage-story-server:latest
    ports:
      - "42420:42420/tcp"
      - "42420:42420/udp"
    # volumes:
    #   - :/app/data # for configuring server, reading logs, backing up saves etc.
    
