services:
  vintage_story:
    image: localdocker/vintage_story:0.4
    ports:
      - "42420:42420/tcp"
      - "42420:42420/udp"
    volumes:
      - :/app/data # for configuring server, reading logs, backing up saves etc.
    
